FROM node:20-alpine

ENV TZ=America/Sao_Paulo
RUN apk add --no-cache tzdata

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY dist/ ./dist/

RUN mkdir -p logs database

CMD ["node", "dist/index.js"]
